### ISSUE TITLE
Zipping big files is bad m'kay?

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#135]
```
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected LargeZipFile exception was raised:
[TAU] 
[TAU] Filesize would require ZIP64 extensions
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/usr/cta/pet/pkgs/taucmdr-latest/bin/tau", line 48, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/commands/__main__.py", line 133, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/__init__.py", line 296, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/cli_view.py", line 87, in main
[TAU]     return cli.execute_command([args.subcommand], args.options, self.module_name)
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/__init__.py", line 296, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/commands/trial/export.py", line 70, in main
[TAU]     return expr.export(trial_numbers=numbers, export_location=export_location, profile_format=profile_format)
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/model/experiment.py", line 432, in export
[TAU]     util.create_archive(profile_format, os.path.join(export_location, archive_file), exportable_files)
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/util.py", line 352, in create_archive
[TAU]     archive.write(item)
[TAU]   File "/usr/cta/pet/pkgs/taucmdr-latest/conda/lib/python2.7/zipfile.py", line 1148, in write
[TAU]     self._writecheck(zinfo)
[TAU]   File "/usr/cta/pet/pkgs/taucmdr-latest/conda/lib/python2.7/zipfile.py", line 1114, in _writecheck
[TAU]     " would require ZIP64 extensions")
[TAU] LargeZipFile: Filesize would require ZIP64 extensions
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/work1/people/jlinford/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by khsa1** [comment]
Fixed in 47d8074.
