### ISSUE TITLE
AttributeError in experiment create when passed an invalid application name

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#140]
Application "SGE" is a typo below, there is no application named "SGE

```
tau exp cre scaling.weeble.knl --targ knl01 --app SGE --meas profile.sample
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected AttributeError exception was raised:
[TAU] 
[TAU] 'NoneType' object has no attribute 'eid'
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/usr/cta/pet/pkgs/taucmdr-latest/bin/tau", line 48, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/commands/__main__.py", line 133, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/__init__.py", line 296, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/cli_view.py", line 87, in main
[TAU]     return cli.execute_command([args.subcommand], args.options, self.module_name)
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/__init__.py", line 296, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/work1/cta/pet/pkgs/taucmdr-latest/bin/../packages/taucmdr/cli/commands/experiment/create.py", line 73, in main
[TAU]     'application': app.eid,
[TAU] AttributeError: 'NoneType' object has no attribute 'eid'
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/work1/people/jlinford/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by khsa1** [comment]
Fixed in 14a555c.
