### ISSUE TITLE
KeyError with KNL and CNL on Cori.

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#171]
```
jlinford@cori09 ~/workspace/openshmem17/applications/ISx $ tau target copy cori09 cori.knl --arch=KNL
[TAU] Added target 'cori.knl' to project configuration 'ISx'.
jlinford@cori09 ~/workspace/openshmem17/applications/ISx $ tau select cori.knl ISx profile
[TAU] Created a new experiment 'cori.knl-ISx-profile'
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected KeyError exception was raised:
[TAU] 
[TAU] (<taucmdr.cf.platforms.Architecture object at 0x2aaaaf717bd0>, <taucmdr.cf.platforms.OperatingSystem object at 
[TAU]     0x2aaaaf717ed0>)
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/global/homes/j/jlinford/workspace/taucmdr-test/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/cli/commands/__main__.py", 
[TAU]     line 133, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/cli/__init__.py", line 292, 
[TAU]     in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/cli/commands/select.py", 
[TAU]     line 177, in main
[TAU]     Experiment.select(name)
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/model/experiment.py", line 
[TAU]     127, in select
[TAU]     proj_ctrl.select(proj, expr)
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/model/project.py", line 119,
[TAU]      in select
[TAU]     experiment.configure()
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/fasteners/process_lock.py", line 
[TAU]     252, in wrapper
[TAU]     return f(*args, **kwargs)
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/model/experiment.py", line 
[TAU]     268, in configure
[TAU]     forced_makefile=target.get('forced_makefile', None))
[TAU]   File 
[TAU]     "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/cf/software/tau_installation.py",
[TAU]      line 286, in __init__
[TAU]     self.tau_magic = TauMagic.find((self.target_arch, self.target_os))
[TAU]   File "/global/project/projectdirs/m88/jlinford/taucmdr-test/bin/../packages/taucmdr/cf/objects.py", line 190, in
[TAU]      find
[TAU]     return cls.__instances__[key]
[TAU] KeyError: (<taucmdr.cf.platforms.Architecture object at 0x2aaaaf717bd0>, <taucmdr.cf.platforms.OperatingSystem 
[TAU]     object at 0x2aaaaf717ed0>)
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/global/u2/j/jlinford/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
jlinford@cori09 ~/workspace/openshmem17/applications/ISx :( $ 





```

**Comment by jlinford** [comment]
Fixed in f2c49ae7470c4068aea4bcbe08e964f315ae77db
