### ISSUE TITLE
tau show x.slog2 breaks, but tau show ./x.slog2 works

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#186]
```
Laurens-MacBook-Air-2:taucmdr-1.2.0 llsmith$ tau show ln1-hamr-1.5.0-trace.trial0.slog2



[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected OSError exception was raised:
[TAU] 
[TAU] [Errno 2] No such file or directory: ''
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/../packages/taucmdr/cli/commands/__main__.py", line 
[TAU]     153, in main
[TAU]     return cli.execute_command(shortcut, cmd_args)
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/../packages/taucmdr/cli/__init__.py", line 298, in 
[TAU]     execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/../packages/taucmdr/cli/commands/trial/show.py", line 
[TAU]     96, in main
[TAU]     return tau.show_data_files(dataset, profile_tools, trace_tools)
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/../packages/taucmdr/cf/software/tau_installation.py", 
[TAU]     line 1295, in show_data_files
[TAU]     retval = launcher(fmt, paths, env)
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/../packages/taucmdr/cf/software/tau_installation.py", 
[TAU]     line 1245, in _show_jumpshot
[TAU]     cwd=cwd, env=env, stdout=False)
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/bin/../packages/taucmdr/util.py", line 474, in 
[TAU]     create_subprocess
[TAU]     stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=1)
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/conda/lib/python2.7/subprocess.py", line 390, in __init__
[TAU]     errread, errwrite)
[TAU]   File "/Users/llsmith/taucmdr-1.2.0/conda/lib/python2.7/subprocess.py", line 1024, in 
[TAU]     _execute_child
[TAU]     raise child_exception
[TAU] OSError: [Errno 2] No such file or directory: ''
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/Users/llsmith/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Laurens-MacBook-Air-2:taucmdr-1.2.0 llsmith$ 
```

**Comment by khsa1** [comment]
Fixed in 96e2cadab131deb49.
