### ISSUE TITLE
Unexpected TypeError

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#187]
```
jlinford@east03:~/examples/mm$ tau measurement create profile.papi --metrics TIME PAPI_FP_INS PAPI_L2_DCA PAPI_L2_DCM
[TAU] Added measurement 'profile.papi' to project configuration 'mm'.
jlinford@east03:~/examples/mm$ tau select profile.papi
[TAU] Created a new experiment 'east03-mm-profile.papi'
[TAU] ******************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] PAPI metrics [PAPI_FP_INS, PAPI_L2_DCA, PAPI_L2_DCM] are not compatible on the current host: PAPI_L2_DCM is not 
[TAU]     compatible with other events.
[TAU] 
[TAU] You may ignore this warning if you are cross-compiling.
[TAU] 
[TAU] ******************************************************************************************************************
[TAU] ******************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] PAPI metrics [PAPI_FP_INS, PAPI_L2_DCA, PAPI_L2_DCM] are not compatible on the current host: PAPI_L2_DCM is not 
[TAU]     compatible with other events.
[TAU] 
[TAU] You may ignore this warning if you are cross-compiling.
[TAU] 
[TAU] ******************************************************************************************************************
[TAU] TAU must be reconfigured: TAU Makefile not found for tags '19cec192, papi' in 
[TAU]     '/home/jlinford/taucmdr-1.2.0.4/system/tau/./tau-2.26.3'
[TAU] Installing TAU Performance System at '/home/jlinford/taucmdr-1.2.0.4/system/tau/./tau-2.26.3'
[TAU] Configuring TAU...
[TAU] Completed in 1.216 seconds                                                                                        [TAU] Compiling and installing TAU...
[TAU] Completed in 9.299 seconds                                                                                        [TAU] Checking installed files...
[TAU] Completed in 0.064 seconds                                                                                        [TAU] Setting file permissions...
[TAU] Completed in 0.114 seconds                                                                                        [TAU] Verifying TAU Performance System installation...
[TAU] ******************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] PAPI metrics [PAPI_FP_INS, PAPI_L2_DCA, PAPI_L2_DCM] are not compatible on the current host: PAPI_L2_DCM is not 
[TAU]     compatible with other events.
[TAU] 
[TAU] You may ignore this warning if you are cross-compiling.
[TAU] 
[TAU] ******************************************************************************************************************
[TAU] Selected experiment 'east03-mm-profile.papi'.
[TAU] Application rebuild required:
[TAU]   - source_inst changed from 'automatic' to 'never'
[TAU]   - metrics changed from [TIME] to [TIME, PAPI_FP_INS, PAPI_L2_DCA, PAPI_L2_DCM]
jlinford@east03:~/examples/mm$ tau meas del profile.papi
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected TypeError exception was raised:
[TAU] 
[TAU] list indices must be integers, not str
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/cli/commands/__main__.py", line 132, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/cli/__init__.py", line 298, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/cli/cli_view.py", line 87, in main
[TAU]     return cli.execute_command([args.subcommand], args.options, self.module_name)
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/cli/__init__.py", line 298, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/cli/cli_view.py", line 181, in main
[TAU]     return self._delete_record(store, key)
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/cli/cli_view.py", line 173, in _delete_record
[TAU]     ctrl.delete({key_attr: key})
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/mvc/controller.py", line 339, in delete
[TAU]     self._disassociate(model, foreign_model, affected_keys, via)
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/mvc/controller.py", line 442, in _disassociate
[TAU]     foreign_model.controller(self.storage).delete(affected)
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/model/experiment.py", line 207, in delete
[TAU]     self._restrict_project(keys)
[TAU]   File "/home/jlinford/taucmdr-1.2.0.4/bin/../packages/taucmdr/model/experiment.py", line 104, in 
[TAU]     _restrict_project
[TAU]     key_dict['project'] = Project.controller(self.storage).selected().eid
[TAU] TypeError: list indices must be integers, not str
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/home/jlinford/.local/taucmdr/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
jlinford@east03:~/examples/mm$ 
```
[debug_log.gz](https://github.com/ParaToolsInc/taucmdr/files/1338800/debug_log.gz)

**Comment by jlinford** [comment]
Whoever fixes this please be sure to make a unit test.

**Comment by jlinford** [comment]
Tests pass!
