### ISSUE TITLE
crash when copy/edit app then change experiment to use new app

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#198]
```
[ibeekman@ln1 hpgmg]$ tau experiment edit ln1-hpgmg-profile-compinst --application hpgmg-noomp
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] An unexpected AttributeError exception was raised:
[TAU]
[TAU] 'NoneType' object has no attribute 'eid'
[TAU]
[TAU] Traceback (most recent call last):
[TAU]   File "/home/ibeekman/taucmdr-1.2.0/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/gpfs/home/ibeekman/taucmdr-1.2.0/bin/../packages/taucmdr/cli/commands/__main__.py", line 132, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/gpfs/home/ibeekman/taucmdr-1.2.0/bin/../packages/taucmdr/cli/__init__.py", line 298, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/gpfs/home/ibeekman/taucmdr-1.2.0/bin/../packages/taucmdr/cli/cli_view.py", line 87, in main
[TAU]     return cli.execute_command([args.subcommand], args.options, self.module_name)
[TAU]   File "/gpfs/home/ibeekman/taucmdr-1.2.0/bin/../packages/taucmdr/cli/__init__.py", line 298, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/gpfs/home/ibeekman/taucmdr-1.2.0/bin/../packages/taucmdr/cli/commands/experiment/edit.py", line 51, in main
[TAU]     data[attr] = record.eid
[TAU] AttributeError: 'NoneType' object has no attribute 'eid'
[TAU]
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/gpfs/home/ibeekman/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU]
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

[debug_log.txt.gz](https://github.com/ParaToolsInc/taucmdr/files/1362875/debug_log.txt.gz)

**Comment by jlinford** [comment]
Should be fixed, please test.

**Comment by zbeekman** [comment]
Fixed on which branch? Also, what's the best way to reinstall/update installed taucmdr? Just another `make clean && make install`?

**Comment by zbeekman** [comment]
Seems to work now. Took quite some time to reinstall taucmdr and re-init a new project.
