### ISSUE TITLE
Cannot add description to tau trial create

### ISSUE THREAD

**Issue by sampollard** [ParaToolsInc/taucmdr#273]
Here is an example command:
`tau trial create --description="gfortran, $OMP_NUM_THREADS threads, default input" ./hfodd < hfodd.d`

This was on the enterprise branch, tag 05a07c8757b2e4a8f260817709abfa741aa13e09

If I do this, I get the following error (though I may have added too much from the debug_log)
```
#####################################################################################################################################################
TAU COMMANDER LOGGING INITIALIZED

Timestamp         : 2018-04-29 18:42:50.151455
Hostname          : arya
Platform          : Linux-4.4.0-38-generic-x86_64-with-debian-stretch-sid
Version           : 0.0.0
Python Version    : 2.7.14
Working Directory : /disks/large/home/users/spollard/nukes
Terminal Size     : 155x33
Frozen            : False
#####################################################################################################################################################

[DEBUG] Detected 72 processors
[DEBUG] tau args: Namespace(command='measurement', options=['list'])
[DEBUG] Arguments: Namespace(command='measurement', options=['list'])
"~/.local/taucmdr/debug_log" 40955L, 4014897C                                                                                               12,1          Top
    return main(perm_args)
  File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/cli_view.py", line 93, in main
    return cli.execute_command([args.subcommand], args.options, self.module_name)
  File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/__init__.py", line 324, in execute_command
    return main(perm_args)
  File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/commands/trial/create.py", line 91, in main
    elif argv[2] in '--description':
IndexError: list index out of range

[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] An unexpected IndexError exception was raised:
[TAU]
[TAU] list index out of range
[TAU]
[TAU] Traceback (most recent call last):
[TAU]   File "/home/users/spollard/local/bin/tau", line 73, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/commands/__main__.py", line 132, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/__init__.py", line 324, in execute_command
[TAU]     return main(perm_args)
[TAU]   File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/cli_view.py", line 93, in main
[TAU]     return cli.execute_command([args.subcommand], args.options, self.module_name)
[TAU]   File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/__init__.py", line 324, in execute_command
[TAU]     return main(perm_args)
[TAU]   File "/disks/large/home/users/spollard/local/bin/../packages/taucmdr/cli/commands/trial/create.py", line 91, in main
[TAU]     elif argv[2] in '--description':
[TAU] IndexError: list index out of range
[TAU]
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/disks/large/home/users/spollard/.local/taucmdr/debug_log' to <support@paratools.com> for assistance.
[TAU]
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by sampollard** [comment]
Oh, what a silly mistake! That did the trick.
