### ISSUE TITLE
Tau Nightly cannot find ompt

### ISSUE THREAD

**Issue by sampollard** [ParaToolsInc/taucmdr#282]
Maybe this is some weird configuration of mine, but when I try to select an experiment with the `--tau nightly` flag turned on, I get the following error:

```
.
.
.
[DEBUG] g++     -DTAU_LIBRARY_SOURCE  -O2 -g -DTAU_MAX_THREADS=112 -DTAU_MAX_METRICS=2 -DTAU_MAX_COUNTERS=2 -I/gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/include -I/gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/packages/papi/5.5.1/src -I/packages/papi/5.5.1/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS                     -DTAU_LINUX_TIMERS                                 -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/gpfs/projects/hpcl/spollard/local/system/libunwind/a3d36f98/include    -DTAU_TRACK_LD_LOADER     -DTAU_OPENMP_NESTED  -DTAU_USE_OMPT_TR6  -DTAU_USE_TLS     -DTAU_PAPI_PERF_RAPL                  -DTAU_ELF_BFD  -fopenmp   -DTAU_OPENMP -DTAU_UNIFY  -fPIC            -I/gpfs/projects/hpcl/spollard/local/system/binutils/7caa709f/include -c TauBfd.cpp
[DEBUG] g++     -DTAU_LIBRARY_SOURCE  -O2 -g -DTAU_MAX_THREADS=112 -DTAU_MAX_METRICS=2 -DTAU_MAX_COUNTERS=2 -I/gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/include -I/gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/packages/papi/5.5.1/src -I/packages/papi/5.5.1/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS                     -DTAU_LINUX_TIMERS                                 -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/gpfs/projects/hpcl/spollard/local/system/libunwind/a3d36f98/include    -DTAU_TRACK_LD_LOADER     -DTAU_OPENMP_NESTED  -DTAU_USE_OMPT_TR6  -DTAU_USE_TLS     -DTAU_PAPI_PERF_RAPL                  -DTAU_ELF_BFD  -fopenmp   -DTAU_OPENMP -DTAU_UNIFY  -fPIC            -c TauDisable.cpp
[DEBUG] g++     -shared      -o   libTauDisable.so  TauDisable.o TauKojakOpariDisable.o
[DEBUG] TauOMPT.cpp:9:18: fatal error: ompt.h: No such file or directory
[DEBUG]  #include <ompt.h>
[DEBUG]                   ^
[DEBUG] compilation terminated.
[DEBUG] ar rcv  libTauDisable.a TauDisable.o TauKojakOpariDisable.o
[DEBUG] a - TauDisable.o
[DEBUG] a - TauKojakOpariDisable.o
[DEBUG] echo "Built" libTauDisable.a
[DEBUG] Built libTauDisable.a
[DEBUG] Installing libTauDisable.a libTauDisable.so in /gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/x86_64/lib
[DEBUG] /bin/cp libTauDisable.a libTauDisable.so /gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/x86_64/lib
[DEBUG] cd /gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/x86_64/lib
[DEBUG] cd /gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/x86_64/lib/shared-disable ; rm -f libTAU.so TAU.dll
[DEBUG] cd /gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/x86_64/lib/shared-disable ; /bin/ln -sf ../libTauDisable.so libTAU.so
[DEBUG] cd /gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/x86_64/lib/shared-disable ; /bin/ln -sf ../libTauDisable.so TAU.dll
[DEBUG] make[1]: *** [TauOMPT.o] Error 1
[DEBUG] make[1]: *** Waiting for unfinished jobs....
[DEBUG] PapiLayer.cpp: In static member function ‘static int PapiLayer::initializePerfRAPL(int)’:
[DEBUG] PapiLayer.cpp:791:92: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
[DEBUG]    ret = PAPI_add_named_event(ThreadList[tid]->EventSet[rapl_cid], "rapl::RAPL_ENERGY_CORES");
[DEBUG]                                                                                             ^
[DEBUG] PapiLayer.cpp:803:90: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
[DEBUG]    ret = PAPI_add_named_event(ThreadList[tid]->EventSet[rapl_cid], "rapl::RAPL_ENERGY_PKG");
[DEBUG]                                                                                           ^
[DEBUG] PapiLayer.cpp:819:90: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
[DEBUG]    ret = PAPI_add_named_event(ThreadList[tid]->EventSet[rapl_cid], "rapl::RAPL_ENERGY_GPU");
[DEBUG]                                                                                           ^
[DEBUG] PapiLayer.cpp:831:91: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
[DEBUG]    ret = PAPI_add_named_event(ThreadList[tid]->EventSet[rapl_cid], "rapl::RAPL_ENERGY_DRAM");
[DEBUG]                                                                                            ^
[DEBUG] make[1]: Leaving directory `/gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly/src/Profile'
[DEBUG] make: *** [install] Error 2
[DEBUG] ['make', 'install', '-j', '55'] returned 2
[DEBUG] Traceback (most recent call last):
  File "/projects/hpcl/spollard/local/bin/tau", line 73, in <module>
    sys.exit(cli_main_cmd.main(sys.argv[1:]))
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/cli/commands/__main__.py", line 132, in main
    return cli.execute_command([cmd], cmd_args)
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/cli/__init__.py", line 324, in execute_command
    return main(perm_args)
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/cli/commands/select.py", line 168, in main
    Experiment.select(name)
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/model/experiment.py", line 214, in select
    proj_ctrl.select(proj, expr)
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/model/project.py", line 124, in select
    experiment.configure()
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/fasteners/process_lock.py", line 252, in wrapper
    return f(*args, **kwargs)
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/model/experiment.py", line 361, in configure
    tau.install()
  File "/gpfs/projects/hpcl/spollard/local/bin/../packages/taucmdr/cf/software/tau_installation.py", line 804, in install
    raise err
SoftwarePackageError: TAU compilation/installation failed
```

Here is the following configure command:
```
cmd=['./configure', '-tag=a3c51e3b', '-arch=x86_64', '-cc=gcc', '-c++=g++', '-fortran=gfortran', '-bfd=/gpfs/projects/hpcl/spollard/local/system/binutils/7caa709f', u'-papi=/packages/papi/5.5.1', '-unwind=/gpfs/projects/hpcl/spollard/local/system/libunwind/a3d36f98', '-openmp', '-ompt=/gpfs/projects/hpcl/spollard/local/system/ompt/7f887099', '-useropt=-O2#-g#-DTAU_MAX_THREADS=112#-DTAU_MAX_METRICS=2#-DTAU_MAX_COUNTERS=2'], cwd='/gpfs/projects/hpcl/spollard/local/system/tau/tau-nightly'
```

I ended up fixing it by changing the configure to ```./configure -tag=a3c51e3b -arch=x86_64 -cc=gcc -c++=g++ -fortran=gfortran -bfd=/gpfs/projects/hpcl/spollard/local/system/binutils/7caa709f -papi=/packages/papi/5.5.1 -unwind=/gpfs/projects/hpcl/spollard/local/system/libunwind/a3d36f98 -openmp -ompt=download -useropt=-O2#-g#-DTAU_MAX_THREADS=112#-DTAU_MAX_METRICS=2#-DTAU_MAX_COUNTERS=2```

(That is, just doing `-ompt=download`). Do you know why this might be happening?

**Comment by nchaimov** [comment]
This should be fixed now, if you delete the cached tau-nightly source and installation to force the use of the latest nightly.
