### ISSUE TITLE
"Critical " message emmited when running tau select <measurement_name>

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#30]
Tau reports Critical - but it seemed to make the selection (based on tau dashboard before and after).   Here is output text:
[dmackay@delphi samplematrixcode]$ tau select drmnew
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected TypeError exception was raised:
[TAU] 
[TAU] unhashable type: 'list'
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/tau", line 49, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cli/commands/__main__.py", line 115, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cli/__init__.py", line 277, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cli/commands/select.py", line 202, in main
[TAU]     proj_ctrl.select(proj, expr)
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/model/project.py", line 136, in select
[TAU]     experiment.configure()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/model/experiment.py", line 257, in configure
[TAU]     return self.configure_tau(prefix, dependencies)
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/model/experiment.py", line 227, in configure_tau
[TAU]     tau.install()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cf/softwar . . . . 
[debug_log-2-23.txt](https://github.com/ParaToolsInc/taucmdr/files/143240/debug_log-2-23.txt)

**Comment by drmackay** [comment]
Wrong log file attached - closing issue.  Will open new one later with correct log file.
