### ISSUE TITLE
Confirm cafrun is working

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#317]
Make sure cafrun is working correctly

Test on: `tau2/examples/caf/pi_ca.f90`

Compiler instrumentation should work with OpenCoarrays.

```
tau cafrun -n 4 ./pi 30000
tau caf pi_ca.f90 -o pi
tau_caf.sh -optCompInst
```

**Comment by zbeekman** [comment]
trying `tau init --caf T --mpi T` with GFortran 7.3 and Open Coarrays installed into my home directory, but on my path, I get:

```
[TAU] System MPI Fortran compiler '/usr/lib64/mpich/bin/mpif90' wraps '/usr/bin/gfortran'
[TAU] System MPI C++ compiler '/usr/lib64/mpich/bin/mpic++' wraps '/usr/bin/g++'
[TAU] System MPI C compiler '/usr/lib64/mpich/bin/mpicc' wraps '/usr/bin/gcc'
[TAU] Created a new project named 'examples'.
[TAU] Added application 'examples' to project configuration 'examples'.
[TAU] Added target 'v' to project configuration 'examples'.
[TAU] Added measurement 'baseline' to project configuration 'examples'.
[TAU] Added measurement 'sample' to project configuration 'examples'.
[TAU] Added measurement 'profile' to project configuration 'examples'.
[TAU] Added measurement 'source-inst' to project configuration 'examples'.
[TAU] Added measurement 'compiler-inst' to project configuration 'examples'.
[TAU] Added measurement 'trace' to project configuration 'examples'.
[TAU] Created a new experiment 'v-examples-sample'
[TAU] TAU must be reconfigured: TAU Makefile not found for tags '062d91f6, mpi' in '/home/vagrant/taucmdr-1.3.0.130/system/tau/./tau-2.28'
[TAU] Installing TAU Performance System at '/home/vagrant/taucmdr-1.3.0.130/system/tau/./tau-2.28'
[TAU] ***************************************************************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] Can't determine TAU magic word for GNU Fortran compiler <taucmdr.cf.compiler.InstalledCompiler object at 0x7efd7d4f4e50>
[TAU] 
[TAU] ***************************************************************************************************************************************************************
[TAU] TAU Performance System installation failed: 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected InternalError exception was raised:
[TAU] 
[TAU] Unknown compiler family for Fortran: 'GNU'
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cli/commands/__main__.py", line 132, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cli/__init__.py", line 321, in execute_command
[TAU]     return main(perm_args)
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cli/commands/initialize.py", line 245, in main
[TAU]     self._populate_project(args)
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cli/commands/initialize.py", line 225, in _populate_project
[TAU]     '--measurement', measurement_name])
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cli/commands/select.py", line 177, in main
[TAU]     Experiment.select(name)
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/model/experiment.py", line 199, in select
[TAU]     proj_ctrl.select(proj, expr)
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/model/project.py", line 115, in select
[TAU]     experiment.configure()
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/fasteners/process_lock.py", line 252, in wrapper
[TAU]     return f(*args, **kwargs)
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/model/experiment.py", line 358, in configure
[TAU]     tau.install()
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cf/software/tau_installation.py", line 891, in install
[TAU]     self.installation_sequence()
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cf/software/tau_installation.py", line 909, in installation_sequence
[TAU]     self.configure()
[TAU]   File "/home/vagrant/taucmdr-1.3.0.130/bin/../packages/taucmdr/cf/software/tau_installation.py", line 738, in configure
[TAU]     raise InternalError("Unknown compiler family for Fortran: '%s'" % fc_family)
[TAU] InternalError
[TAU] 
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/home/vagrant/.local/taucmdr/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by khsa1** [comment]
Does it work if you add the `--caf-fc caf` option?
