### ISSUE TITLE
OSX 10.14.6 install fails (master)

### ISSUE THREAD

**Issue by brnorris03** [ParaToolsInc/taucmdr#329]
Freshly cloned master, make install fails with:

```
writing list of installed files to '/Users/norris/soft/taucmdr/install.log'
/Users/norris/soft/taucmdr/system/configure --tau-config=minimal
[TAU] **********************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] Compiler '/usr/bin/c++' is a System compiler, not a Apple compiler.
[TAU] 
[TAU] **********************************************************************************************
[TAU] **********************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] Compiler '/usr/bin/cc' is a System compiler, not a Apple compiler.
[TAU] 
[TAU] **********************************************************************************************
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] Apple compilers (required to build TAU) could not be found.
[TAU] 
[TAU] Hint: Try `configure --help`
[TAU] 
[TAU] Please check the selected experiment or send '/Users/norris/.local/taucmdr/debug_log' to 
[TAU]     <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
make: *** [install] Error 156
```

The compiler is whatever comes with the latest xcode:

```
$ cc -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Here is a relevant chunk of the debug log:
```
[DEBUG] Apple C compiler is '/usr/bin/cc'
[DEBUG] (/usr/bin/cc, Host_CC) not in compiler cache
[DEBUG] UID: (62d5a1db40b489a10d9e20a040cbec3b9d641312): ['/usr/bin/cc', 'Apple', 'Host_CC']
[DEBUG] Checking subprocess output: ['/usr/bin/cc', '--version', '-E']
[DEBUG] ['/usr/bin/cc', '--version', '-E'] returned 0
[DEBUG] Probing compiler '/usr/bin/cc' to discover compiler family
[DEBUG] Checking subprocess output: ['/usr/bin/cc', '-craype-verbose', '--version', '-E']
[DEBUG] ['/usr/bin/cc', '-craype-verbose', '--version', '-E'] returned 1: clang: error: unknown argument: '-craype-verbose'
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

[DEBUG] '/usr/bin/cc' is not a Apple compiler
[DEBUG] Checking subprocess output: ['/usr/bin/cc', '-craype-verbose', '--version', '-E']
[DEBUG] ['/usr/bin/cc', '-craype-verbose', '--version', '-E'] returned 1: clang: error: unknown argument: '-craype-verbose'
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

[DEBUG] '/usr/bin/cc' is not a Cray compiler
[DEBUG] Checking subprocess output: ['/usr/bin/cc', '-craype-verbose', '--version', '-E']
[DEBUG] ['/usr/bin/cc', '-craype-verbose', '--version', '-E'] returned 1: clang: error: unknown argument: '-craype-verbose'
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

[DEBUG] '/usr/bin/cc' is not a Cray compiler
[TAU] ************************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] Compiler '/usr/bin/cc' is a System compiler, not a Apple compiler.
[TAU] 
[TAU] ************************************************************************************************************************
[DEBUG] Traceback (most recent call last):
  File "/Users/norris/soft/taucmdr/system/configure", line 217, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/norris/soft/taucmdr/system/configure", line 204, in main
    tau_prefix = _configure_minimal(args)
  File "/Users/norris/soft/taucmdr/system/configure", line 174, in _configure_minimal
    tau = TauInstallation.get_minimal()
  File "/Users/norris/soft/taucmdr/system/../packages/taucmdr/cf/software/tau_installation.py", line 470, in get_minimal
    raise SoftwarePackageError("%s compilers (required to build TAU) could not be found." % target_family)
SoftwarePackageError: Apple compilers (required to build TAU) could not be found.
```

[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/3952994/debug_log.txt)

**Comment by nchaimov** [comment]
Investigating this. It appears that Apple changed the format of the response to “clang —version” in Xcode 11.

**Comment by nchaimov** [comment]
@brnorris03 I have pushed a change to the unstable branch so that TAU Commander will detect the Xcode 11 version of Clang as an Apple compiler. Can you test with the unstable branch and report whether it resolves the issue?
