### ISSUE TITLE
Compiler detection errors on Cray

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#395]
Sameer reports that on Narwhal at Navy DSRC (a Cray XC system) with Intel compilers 2021.1, MPI is not detected:

```
[TAU] CRITICAL
[TAU] 
[TAU] mpi = True in measurement requires MPI_CC be defined in target but it is undefined
[TAU] 
[TAU] Hint: Try `tau --help
```

and the Fortran compiler is not detected correctly:

```
[TAU] Verifying GNU Binutils installation...
[TAU] Installing TAU Performance System at '/p/home/sameer/pkgs/taucommander/system/tau/./tau-2.30.2'
[TAU] *******************************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] Can't determine TAU magic word for System Fortran compiler <taucmdr.cf.compiler.InstalledCompiler object at 0x7f42bd5b0310>
[TAU] 
[TAU] *******************************************************************************************************************************
[TAU] TAU Performance System installation failed: 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected InternalError exception was raised:
[TAU] 
[TAU] Unknown compiler family for Fortran: 'System'
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cli/commands/__main__.py", line 131, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cli/__init__.py", line 319, in execute_command
[TAU]     return main(perm_args)
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cli/commands/initialize.py", line 245, in main
[TAU]     self._populate_project(args)
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cli/commands/initialize.py", line 225, in _populate_project
[TAU]     '--measurement', measurement_name])
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cli/commands/select.py", line 177, in main
[TAU]     Experiment.select(name)
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/model/experiment.py", line 185, in select
[TAU]     proj_ctrl.select(proj, expr)
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/model/project.py", line 118, in select
[TAU]     experiment.configure()
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/fasteners/process_lock.py", line 252, in wrapper
[TAU]     return f(*args, **kwargs)
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/model/experiment.py", line 347, in configure
[TAU]     tau.install()
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cf/software/tau_installation.py", line 968, in install
[TAU]     self.installation_sequence()
[TAU]   File "/p/home/sameer/pkgs/taucommander/bin/../packages/taucmdr/cf/software/tau_installation.py", line 986, in 
[TAU]     installation_sequence
```

during `tau init --mpi --compiler-inst always`

**Comment by nchaimov** [comment]
This appears to work correctly on Cori, although Cori has Intel 19 compilers. I wonder if the problem is related to Intel's changing of the version numbering scheme to full years (19.1 vs 2021.1)

**Comment by khsa1** [comment]
When using the OneAPI compilers, the Cray compilers use the LLVM-based compilers  (icx and icpx).  The MPI detection issue is resolved in #403. 

A new issue comes up during initialization, shown below. I believe this is related to this [issue](https://github.com/libunwind/libunwind/issues/154). I also confirmed that this error appears with gcc/g++ 10. Could we update the version of libunwind?

```
[TAU] Compiling libunwind...
[TAU]  [2.260 seconds]
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT Lperf-simple.o -MD -MP -MF $depbase.Tpo -c -o Lperf-simple.o Lperf-simple.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo Gperf-trace.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT Gperf-trace.o -MD -MP -MF $depbase.Tpo -c -o Gperf-trace.o Gperf-trace.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo Lperf-trace.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT Lperf-trace.o -MD -MP -MF $depbase.Tpo -c -o Lperf-trace.o Lperf-trace.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo mapper.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT mapper.o -MD -MP -MF $depbase.Tpo -c -o mapper.o mapper.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo test-ptrace-misc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT test-ptrace-misc.o -MD -MP -MF $depbase.Tpo -c -o test-ptrace-misc.o test-ptrace-misc.c
&&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo ident.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT ident.o -MD -MP -MF $depbase.Tpo -c -o ident.o ident.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo crasher.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT crasher.o -MD -MP -MF $depbase.Tpo -c -o crasher.o crasher.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo test-coredump-unwind.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/opt/cray/pe/craype/2.7.10/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -MT test-coredump-unwind.o -MD -MP -MF $depbase.Tpo -c -o test-coredump-unwind.o test-coredu
mp-unwind.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o crasher crasher.o
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare -static  -o forker forker.o
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o mapper mapper.o
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o test-ptrace-misc test-ptrace-misc.o ident.o
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o test-coredump-unwind test-coredump-unwind.o ../src/libunwind-coredump.la ../src/libunwind-x86_64.la
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Lperf-trace Lperf-trace.o ../src/libunwind.la
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Gperf-trace Gperf-trace.o ../src/libunwind-x86_64.la ../src/libunwind.la
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o crasher crasher.o
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Gperf-simple Gperf-simple.o ../src/libunwind-x86_64.la ../src/libunwind.la
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o forker forker.o
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Lperf-simple Lperf-simple.o ../src/libunwind.la
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o mapper mapper.o
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o test-ptrace-misc test-ptrace-misc.o ident.o
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Lperf-trace Lperf-trace.o  ../src/.libs/libunwind.a -lc -lgcc_s
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Lperf-simple Lperf-simple.o  ../src/.libs/libunwind.a -lc -lgcc_s
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o test-coredump-unwind test-coredump-unwind.o  ../src/.libs/libunwind-coredump.a ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3
.1/src/.libs/libunwind.a -lgcc_s -lc
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Gperf-trace Gperf-trace.o  ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a ../src/.libs/libunwind.a -l
c -lgcc_s
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Gperf-simple Gperf-simple.o  ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a ../src/.libs/libunwind.a
-lc -lgcc_s
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a(Linit.o):(.bss+0x66e8): multiple definition of `_U_dyn_info_list'; ../src/.libs/libunwind-x86_64.a(Ginit.
o):(.bss+0x66e8): first defined here
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a(Linit.o):(.bss+0x66e8): multiple definition of `_U_dyn_info_list'; ../src/.libs/libunwind-x86_64.a(Ginit.
o):(.bss+0x66e8): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1214: test-coredump-unwind] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1062: Gperf-trace] Error 1
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
make: *** [Makefile:589: all-recursive] Error 1
[TAU]  [0.602 seconds]
Making all in src
make[1]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make  all-am
make[2]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
Making all in tests
make[1]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Gperf-trace Gperf-trace.o ../src/libunwind-x86_64.la ../src/libunwind.la
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Gperf-trace Gperf-trace.o  ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a ../src/.libs/libunwind.a -l
c -lgcc_s
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a(Linit.o):(.bss+0x66e8): multiple definition of `_U_dyn_info_list'; ../src/.libs/libunwind-x86_64.a(Ginit.
o):(.bss+0x66e8): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1062: Gperf-trace] Error 1
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
make: *** [Makefile:589: all-recursive] Error 1
[TAU] Installing libunwind...
[TAU]  [0.887 seconds]
libtool: install: /usr/bin/install -c .libs/libunwind-setjmp.a /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-setjmp.a
libtool: install: chmod 644 /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-setjmp.a
libtool: install: ranlib /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-setjmp.a
libtool: finish: PATH="/opt/cray/pe/gcc/10.3.0/bin:/p/home/skhuvis/src/taucmdr/scripts:/p/app/mpscp-1.3a/bin:/opt/cray/pe/pals/1.0.17/bin:/opt/cray/pe/perftools/21.09.0/bin:/opt/cray/pe/papi/6.0.0.9/bin:/opt/cray/libfabric/1.11.0.4.91/bi
n:/opt/cray/pe/craype/2.7.10/bin:/opt/intel/oneapi_2021.3.0.3219/mkl/2021.3.0/bin/intel64:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/lib/oclfpga/llvm/aocl-bin:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/lib/oclfp
ga/bin:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/bin/intel64:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/p/home/skhuvis/.local/bin:/usr/bin:/bin:/op
t/c3/bin:/opt/pbs/bin:/sbin:/bin:/opt/cray/pe/bin:/app/bin:/usr/local/bin:/app/COTS/bin:/usr/local/krb5/bin:/p/app/BCT/bin:/p/app/SLB:/sbin" ldconfig -n /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make  install-exec-hook
make[4]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
if test -f /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.a; then \
        cd /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib && ln -s -f libunwind-x86_64.a libunwind-generic.a; \
fi
if test -f /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.so; then \
        cd /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib && ln -s -f libunwind-x86_64.so \
        libunwind-generic.so; \
fi
make[4]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[3]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[2]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
Making install in tests
make[1]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Gperf-trace Gperf-trace.o ../src/libunwind-x86_64.la ../src/libunwind.la
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o test-coredump-unwind test-coredump-unwind.o ../src/libunwind-coredump.la ../src/libunwind-x86_64.la
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Gperf-trace Gperf-trace.o  ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a ../src/.libs/libunwind.a -l
c -lgcc_s
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o test-coredump-unwind test-coredump-unwind.o  ../src/.libs/libunwind-coredump.a ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3
.1/src/.libs/libunwind.a -lgcc_s -lc
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a(Linit.o):(.bss+0x66e8): multiple definition of `_U_dyn_info_list'; ../src/.libs/libunwind-x86_64.a(Ginit.
o):(.bss+0x66e8): first defined here
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a(Linit.o):(.bss+0x66e8): multiple definition of `_U_dyn_info_list'; ../src/.libs/libunwind-x86_64.a(Ginit.
o):(.bss+0x66e8): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1062: Gperf-trace] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1214: test-coredump-unwind] Error 1
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
make: *** [Makefile:589: install-recursive] Error 1
[TAU]  [0.894 seconds]
libtool: install: ranlib /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-coredump.a
libtool: install: /usr/bin/install -c .libs/libunwind-x86_64.a /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.a
libtool: install: chmod 644 /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.a
libtool: install: ranlib /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.a
libtool: install: /usr/bin/install -c .libs/libunwind-setjmp.a /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-setjmp.a
libtool: install: chmod 644 /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-setjmp.a
libtool: install: ranlib /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-setjmp.a
libtool: finish: PATH="/opt/cray/pe/gcc/10.3.0/bin:/p/home/skhuvis/src/taucmdr/scripts:/p/app/mpscp-1.3a/bin:/opt/cray/pe/pals/1.0.17/bin:/opt/cray/pe/perftools/21.09.0/bin:/opt/cray/pe/papi/6.0.0.9/bin:/opt/cray/libfabric/1.11.0.4.91/bi
n:/opt/cray/pe/craype/2.7.10/bin:/opt/intel/oneapi_2021.3.0.3219/mkl/2021.3.0/bin/intel64:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/lib/oclfpga/llvm/aocl-bin:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/lib/oclfp
ga/bin:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/bin/intel64:/opt/intel/oneapi_2021.3.0.3219/compiler/2021.3.0/linux/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/p/home/skhuvis/.local/bin:/usr/bin:/bin:/op
t/c3/bin:/opt/pbs/bin:/sbin:/bin:/opt/cray/pe/bin:/app/bin:/usr/local/bin:/app/COTS/bin:/usr/local/krb5/bin:/p/app/BCT/bin:/p/app/SLB:/sbin" ldconfig -n /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make  install-exec-hook
make[4]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
if test -f /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.a; then \
        cd /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib && ln -s -f libunwind-x86_64.a libunwind-generic.a; \
fi
if test -f /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/libunwind-x86_64.so; then \
        cd /p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib && ln -s -f libunwind-x86_64.so \
        libunwind-generic.so; \
fi
make[4]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
 /usr/bin/mkdir -p '/p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/pkgconfig'
 /usr/bin/install -c -m 644 libunwind-generic.pc unwind/libunwind.pc ptrace/libunwind-ptrace.pc setjmp/libunwind-setjmp.pc coredump/libunwind-coredump.pc '/p/home/skhuvis/src/taucmdr/system/libunwind/54bf6711/lib/pkgconfig'
make[3]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[2]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/src'
Making install in tests
make[1]: Entering directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
/bin/sh ../libtool  --tag=CC   --mode=link /opt/cray/pe/craype/2.7.10/bin/cc  -fPIC -fexceptions -Wall -Wsign-compare   -o Gperf-trace Gperf-trace.o ../src/libunwind-x86_64.la ../src/libunwind.la
libtool: link: /opt/cray/pe/craype/2.7.10/bin/cc -fPIC -fexceptions -Wall -Wsign-compare -o Gperf-trace Gperf-trace.o  ../src/.libs/libunwind-x86_64.a /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a ../src/.libs/libunwind.a -l
c -lgcc_s
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /dev/shm/tmpkkie6wld/libunwind-1.3.1/src/.libs/libunwind.a(Linit.o):(.bss+0x66e8): multiple definition of `_U_dyn_info_list'; ../src/.libs/libunwind-x86_64.a(Ginit.
o):(.bss+0x66e8): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1062: Gperf-trace] Error 1
make[1]: Leaving directory '/dev/shm/tmpkkie6wld/libunwind-1.3.1/tests'
make: *** [Makefile:589: install-recursive] Error 1
[TAU] libunwind installation failed: libunwind installation failed
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] libunwind installation failed
[TAU]
[TAU] Hint: Try `tau --help`
[TAU]
[TAU] Please check the selected experiment or send '/p/home/skhuvis/.local/taucmdr/debug_log' to <support@paratools.com> for assistance.
[TAU]
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/p/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/util.py", line 84, in _cleanup_dtemp
    shutil.copytree(os.path.normpath(dir), dst)
  File "/usr/lib64/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/tmpkkie6wld/libunwind-1.3.1'
```

**Comment by nchaimov** [comment]
Fixed in https://github.com/ParaToolsInc/taucmdr/pull/403
