### ISSUE TITLE
Setting source of dependencies results in error

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#410]
We allow the option to set the location/source of dependencies to None but make the assumption that they are available. This results in errors such as:
```
$ tau init --libelf None

[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[TAU]
[TAU] CRITICAL
[TAU]
[TAU] An unexpected KeyError exception was raised:
[TAU]
[TAU] 'libelf'
[TAU]
[TAU] Traceback (most recent call last):
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/commands/initialize.py", line 245, in main
[TAU]     proj = proj_ctrl.selected()
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/model/project.py", line 125, in selected
[TAU]     selected = self.one(self.storage['selected_project'])
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/storage/storage_dispatch.py", line 109, in __getitem__
[TAU]     return self._get_storage()[key]
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/storage/local_file.py", line 108, in __getitem__
[TAU]     record = self.get({'key': key})
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/storage/local_file.py", line 293, in get
[TAU]     table = self.table(table_name)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/storage/local_file.py", line 239, in table
[TAU]     self.connect_database()
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/storage/local_file.py", line 180, in connect_database
[TAU]     util.mkdirp(self.prefix)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/storage/project.py", line 159, in prefix
[TAU]     raise ProjectStorageError(cwd)
[TAU] taucmdr.cf.storage.project.ProjectStorageError
[TAU] During handling of the above exception, another exception occurred:
[TAU]
[TAU] Traceback (most recent call last):
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/commands/select.py", line 167, in main
[TAU]     Experiment.select(name)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/model/experiment.py", line 180, in select
[TAU]     "There is no experiment named '{}' in project '{}'.".format(name, proj['name']))
[TAU] taucmdr.error.ExperimentSelectionError: There is no experiment named 'talapas-ln1-1-sample' in project '1'.
[TAU]
[TAU] During handling of the above exception, another exception occurred:
[TAU]
[TAU] Traceback (most recent call last):
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/tau", line 69, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/commands/__main__.py", line 130, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/__init__.py", line 319, in execute_command
[TAU]     return main(perm_args)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/commands/initialize.py", line 252, in main
[TAU]     self._populate_project(args)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/commands/initialize.py", line 230, in _populate_project
[TAU]     '--measurement', measurement_name])
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cli/commands/select.py", line 176, in main
[TAU]     Experiment.select(name)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/model/experiment.py", line 185, in select
[TAU]     proj_ctrl.select(proj, expr)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/model/project.py", line 117, in select
[TAU]     experiment.configure()
[TAU]   File "/home/skhuvis/.local/lib/python3.6/site-packages/fasteners/process_lock.py", line 572, in wrapper
[TAU]     return f(*args, **kwargs)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/model/experiment.py", line 347, in configure
[TAU]     unwind_depth=measurement.get_or_default('unwind_depth'))
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/software/tau_installation.py", line 457, in __init__
[TAU]     self.add_dependency(pkg, sources)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/software/installation.py", line 401, in add_dependency
[TAU]     self.dependencies[name] = cls(sources, self.target_arch, self.target_os, self.compilers, *args, **kwargs)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/software/libdwarf_installation.py", line 51, in __init__
[TAU]     self.add_dependency('libelf', sources)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/software/installation.py", line 401, in add_dependency
[TAU]     self.dependencies[name] = cls(sources, self.target_arch, self.target_os, self.compilers, *args, **kwargs)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/software/libelf_installation.py", line 49, in __init__
[TAU]     target_arch, target_os, compilers, REPOS, None, LIBRARIES, HEADERS)
[TAU]   File "/gpfs/home/skhuvis/src/taucmdr/scripts/../packages/taucmdr/cf/software/installation.py", line 148, in __init__
[TAU]     src = sources[name]
[TAU] KeyError: 'libelf'
[TAU]
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/gpfs/home/skhuvis/.local/taucmdr/debug_log' to <support@paratools.com> for assistance.
[TAU]
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by nchaimov** [comment]
Fixed by #411
