### ISSUE TITLE
Nightly test: No module named 'taucmdr.cf.software.level_zero_installation' error

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#417]
An error is occurring in the Nightly test when attempting to do a full build (all TAU configurations):

```
 CRITICAL
 An unexpected ModuleNotFoundError exception was raised:
 
 No module named 'taucmdr.cf.software.level_zero_installation'
 
 Traceback (most recent call last):
   File "/home/runner/taucmdr/system/configure", line 216, in <module>
     sys.exit(main(sys.argv[1:]))
   File "/home/runner/taucmdr/system/configure", line 205, in main
     tau_prefix = _configure_full(args)
   File "/home/runner/taucmdr/system/configure", line 168, in 
     _configure_full
     _configure_project(args)
   File "/home/runner/taucmdr/system/configure", line 120, in 
     _configure_project
     targ.acquire_sources()
   File "/home/runner/taucmdr/system/../packages/taucmdr/model/target.py", 
     line 648, in acquire_sources
     inst = self.get_installation(attr.replace('_source', ''))
   File "/home/runner/taucmdr/system/../packages/taucmdr/model/target.py", 
     line 641, in get_installation
     cls = software.get_installation(name)
   File 
     "/home/runner/taucmdr/system/../packages/taucmdr/cf/software/__init__.py",
      line 44, in get_installation
     pkg = __import__(__name__+'.'+module_name, globals(), locals(), 
     [cls_name])
 ModuleNotFoundError: No module named 
     'taucmdr.cf.software.level_zero_installation'
 
 This is a bug in TAU Commander.
 Please send '/home/runner/.local/taucmdr/debug_log' to 
     <support@paratools.com> for assistance.
```

It appears that TAU Commander is attempting to build a TAU configuration which uses Intel level0 support, and is attempting to download level0. TAU Commander should not attempt to download level0 if it is not available, as this is part of Intel oneAPI and not something we can manage ourselves. Also, a build of TAU using level0 should not be done in an environment like the testing environment where level0 is not already installed.

**Comment by nchaimov** [comment]
Fixed by #418
