### ISSUE TITLE
Export trace files

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#65]
It is currently only possible to export profile files, but  tau commander should be able to export trace files as well. Attempting to export a trace experiment results in the following error:
edu.uoregon.tau.perfdmf.DataSourceException: profiles type: no profiles specified
    at edu.uoregon.tau.perfdmf.UtilFncs.initializeDataSource(UtilFncs.java:546)
    at edu.uoregon.tau.perfdmf.UtilFncs.initializeDataSource(UtilFncs.java:513)
    at edu.uoregon.tau.paraprof.ParaProf.main(ParaProf.java:663)

**Comment by khsa1** [comment]
Fixed in e6159f81fd.
