### ISSUE TITLE
mpif77 wraps g77 causes list index out of range

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#83]
Test on riptide:

[TAU] *********************************************************************************************************************************************************************
[TAU] 
[TAU] WARNING
[TAU] 
[TAU] '/gpfs/pkgs/mhpcc/intel/2013/impi/4.1.0.024/intel64/bin/mpif77' wraps an unrecognized compiler command '/usr/bin/g77'. TAU will attempt to continue but may fail 
[TAU]     later on.
[TAU] 
[TAU] *********************************************************************************************************************************************************************
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected IndexError exception was raised:
[TAU] 
[TAU] list index out of range
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/bin/tau", line 48, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/commands/__main__.py", line 146, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/__init__.py", line 277, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/commands/initialize.py", line 213, in main
[TAU]     self._populate_project(argv, args)
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/commands/initialize.py", line 161, in _populate_project
[TAU]     _safe_execute(target_create_cmd, target_argv)
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/commands/initialize.py", line 135, in _safe_execute
[TAU]     retval = cmd.main(argv)
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/commands/target/create.py", line 225, in main
[TAU]     compilers = self.parse_compiler_flags(args)
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cli/commands/target/create.py", line 72, in parse_compiler_flags
[TAU]     family_comps = InstalledCompilerFamily(family_cls(family_arg))
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cf/compiler/installed.py", line 315, in __init__
[TAU]     installed = InstalledCompiler(absolute_path, info)
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cf/compiler/installed.py", line 160, in __init__
[TAU]     self.wrapped = self._probe_wrapper()
[TAU]   File "/gpfs/pkgs/hpcmp/PTOOLS/pkgs/taucmdr-0.1/conda/lib/python2.7/site-packages/tau/cf/compiler/installed.py", line 199, in _probe_wrapper
[TAU]     wrapped_command = parts[0]
[TAU] IndexError: list index out of range
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/gpfs/home/jlinford/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[jlinford@riptide03 mm]$ module list
Currently Loaded Modulefiles:
  1) intel/13.0   2) impi/4.1     3) costinit
[jlinford@riptide03 mm]$ tau init --compilers Intel --mpi-compilers Intel
[TAU] *********************************************************************************************************************************************************************

**Comment by jlinford** [comment]
Resolved in e4eac75bcc36a8d4cc2b4dc30430d8bf04477575
